image: rocker/verse

stages:
  - TestPackage

before_script:
  - apt-get update
  - r -e 'install.packages(c("devtools", "roxygen2", "testthat", "covr"))'
  - r -e 'devtools::install_deps()'

documentation:
  stage: TestPackage
  script:
    - r -e 'devtools::document()'

check:
  stage: TestPackage
  script:
    - pwd
    - r -e 'devtools::build()'
    - ls -la
    - ls -la ..
    - R CMD check --as-cran ..\rjdiotperso_0.0.2.tar.gz

unittests:
  stage: TestPackage
  script:
    - r -e 'devtools::test()'

codecov:
  stage: TestPackage
  script:
    - r -e 'covr::codecov()'

install:
  stage: TestPackage
  script:
    - r -e 'devtools::install()'
